---
base:
  debug_mode: debug
  time_location: Asia/Chongqing

http:
  addr: :8880
  pid_path: './pid'
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 20
  allow_ip:
    - 127.0.0.1
    - 192.168.1.1

log:
  level: trace
  layout: '2006-01-02T15:04:05.000'
  take_up: false
  file_writer:
    open: true
    log_path: ./logs/gin_scaffold.inf.log
    rotate_log_path: './logs/gin_scaffold.inf.log.%Y%M%D%H'
    wf_log_path: ./logs/gin_scaffold.wf.log
    rotate_wf_log_path: './logs/gin_scaffold.wf.log.%Y%M%D%H'
  console_writer:
    open: false
    color: true

swagger:
  title: gin_scaffold swagger API
  desc: This is a sample server celler server.
  host: 127.0.0.1:8880
  base_path: ""